import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ReactQueryProvider from "@/components/provider/react-query.provider";
import { Toaster } from "@/components/ui/sonner";
import NextAuthSessionProvider from "@/components/provider/nextauth.provider";
import { NotificationProvider } from "@/components/provider/notification.provider";
import { getServerSession } from "next-auth";
import { nextAuthConfig } from "@/configs/auth.config";

const publicSans = Public_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Employee Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthConfig);
  return (
    <html
      lang="en"
      className={publicSans.variable}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider session={session}>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NotificationProvider>
                <Toaster />
                {children}
              </NotificationProvider>
            </ThemeProvider>
          </ReactQueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html >
  );
}
